from enum import Enum

class ResponseSignal(Enum):
    FILE_TYPE_NOT_SUPPORTED = "file type is not supported"
    FILE_SIZE_EXCEEDED = "file size exceeds the maximum limit"
    FILE_UPLOAD_SUCCESS = "successfully validated the uploaded file"
    FILE_UPLOAD_FAILED = "file upload failed"
    FILE_VALIDATION_FAILED = "file validation failed"
    FILE_PROCESSING_FAILED = "file processing failed"
    FILE_PROCESSING_SUCCESS = "file processing succeeded"
    FILE_ID_NOT_FOUND = "file id not found"
    NO_FILES_ERROR = "no files found for this project"
    PROJECT_NOT_FOUND_ERROR = "project not found"
    PROJECT_LIST_SUCCESS = "projects listed successfully"
    ASSETS_LIST_SUCCESS = "assets listed successfully"
    INSERT_INTO_VECTORDB_ERROR = "insert into vector db failed"
    INSERT_INTO_VECTORDB_SUCCESS = "insert into vector db succeeded"
    VECTORDB_COLLECTION_RETRIEVED = "vector db collection retrieved"
    VECTORDB_SEARCH_ERROR = "vector db search failed"
    VECTORDB_SEARCH_SUCCESS = "vector db search succeeded"
    RAG_ANSWER_ERROR = "rag answer failed"
    RAG_ANSWER_SUCCESS = "rag answer succeeded"
